### ISSUE TITLE
Hi, I need help how to run object brawl mr.vitalik in C# plz I will be grateful if you help :)

### ISSUE THREAD

**Issue by yamixdev** [VitalikObject/BrawlStars-Server#10]
Hi, I need help how to run object brawl mr.vitalik in C# plz I will be grateful if you help :)

**Comment by Super-brawl-team** [comment]
By running it 💀

**Comment by MehmetRzmx** [comment]
Codeleri doğru girdin mi?

**Comment by Super-brawl-team** [comment]
> Codeleri doğru girdin mi?

Tchec ?
